---
- name: Add EE Cloud Services Execution Environment
  awx.awx.execution_environment:
    name: Cloud Services Execution Environment
    description: Red Hat Cloud Services EE
    organization: "{{ awx_organization | default('') }}"
    image: registry.redhat.io/ansible-automation-platform-22/ee-cloud-services-rhel8:latest
    credential: Red Hat Registry
    state: present
  tags:
    - ees

- name: Add Test Cloud Execution Environment
  awx.awx.execution_environment:
    name: Harwell - Cloud EE
    image: quay.io/scottharwell/cloud-ee:latest
    state: present
  register: harwell_ee
  tags:
    - ees

- name: Set EE as global default
  ansible.builtin.set_fact:
    default_execution_environment: "{{ harwell_ee.id | int }}"
