---
- name: Delete Demo Template
  awx.awx.job_template:
    name: Demo Job Template
    state: absent
  when: (delete_demo_project is defined) and (delete_demo_project|bool)

- name: Azure - Create Resource Group
  awx.awx.job_template:
    name: lab.azure_roles.create_resource_group
    inventory: localhost
    playbook: playbooks/create_resource_group.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group_name: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
    credentials:
      - Azure Service Principal

- name: Azure - Create RHEL VM
  awx.awx.job_template:
    name: lab.azure_roles.create_rhel_vm
    inventory: localhost
    playbook: playbooks/create_rhel_vm.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group_name: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      vm_name: create-rhel-test
      nic_name: create-rhel-test-nic
      network_sec_group_name: create-rhel-test-sg
      public_ip_name: create-rhel-test-public-ip
      vnet_name: spoke-1-vnet
      subnet_name: spoke-1-subnet
      create_public_ip: true
      ssh_public_key: "" # Copy value into this field
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal

- name: Azure - Create Windows Server VM
  awx.awx.job_template:
    name: lab.azure_roles.create_windows_vm
    inventory: localhost
    playbook: playbooks/create_windows_vm.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group_name: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      vm_name: create-win-test
      nic_name: create-win-test-nic
      network_sec_group_name: create-win-test-sg
      public_ip_name: create-win-test-public-ip
      vnet_name: spoke-1-vnet
      subnet_name: spoke-1-subnet
      create_public_ip: true
      ssh_public_key:  "" # Copy value into this field
      admin_password: "" # Set a password value
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal

- name: Azure - Destroy Resource Group
  awx.awx.job_template:
    name: lab.azure_roles.delete_resource_group
    inventory: localhost
    playbook: playbooks/delete_resource_group.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group_name: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
    credentials:
      - Azure Service Principal

- name: Azure - Create Network Peering Demo
  awx.awx.job_template:
    name: lab.azure_roles.create_transit_network
    inventory: localhost
    playbook: playbooks/create_transit_network.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group_name: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      priv_network_hosts_pattern: 172.16.*
      priv_network_ssh_user: azureuser
      ansible_ssh_private_key_file_local_path: ~/.ssh/id_rsa_azure_demo # Must exist locally or be mapped in an EE
      ansible_ssh_private_key_file_dest_path: ~/.ssh/id_rsa_azure_demo
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal

- name: Azure - Destroy Network Peering Demo
  awx.awx.job_template:
    name: lab.azure_roles.delete_transit_network
    project: Ansible Cloud Content Lab - Azure Roles
    playbook: playbooks/delete_transit_network.yml
    inventory: localhost
    extra_vars:
      resource_group_name: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal

- name: Azure - Run DNF Update
  awx.awx.job_template:
    name: lab.azure_roles.update_rhel_vms
    job_type: run
    project: Ansible Cloud Content Lab - Azure Roles
    playbook: playbooks/update_rhel_vms.yml
    inventory: localhost
    limit: RHEL
    credentials:
      - Azure VM SSH Credential
    become_enabled: true
    job_slice_count: 1
    state: present

- name: Run Ephemeral Workload Test
  awx.awx.job_template:
    name: Azure Demos - Ephemeral Workload Test
    job_type: run
    project: Ansible - Azure Demo
    playbook: project/emphemeral_workload_test.yml
    inventory: localhost
    credentials:
      - Ansible Automation Controller
      - Azure Service Principal
      - Azure VM SSH Credential
    become_enabled: true
    job_slice_count: 1
    state: present
