---
namespace: aoc
name: controller_demo_config
version: 2.1.0
authors:
  - Scott Harwell (@scottharwell)
description: A collection of content for setting up Ansible on Cloud demos rapidly.
documentation: ''
homepage: https://github.com/ansible-content-lab/aoc.controller_demo_config
issues: https://github.com/ansible-content-lab/aoc.controller_demo_config/issues
license_file: LICENSE
readme: README.md
repository: https://github.com/ansible-content-lab/aoc.controller_demo_config.git
tags:
  - cloud
  - azure
  - infrastructure
dependencies:
  awx.awx: '>=21.2.0'
build_ignore:
  - '.tox'
  - '.git'
  - '.github'
  - '.gitignore'