---
namespace: ansible_on_clouds
name: setup_and_config
version: 2.0.0
authors:
  - Scott Harwell (@scottharwell)
description: A collection of content for setting up Ansible on Cloud demos rapidly.
documentation: ''
homepage: https://github.com/scottharwell/ansible_on_clouds.setup_and_config
issues: https://github.com/scottharwell/ansible_on_clouds.setup_and_config/issues
license_file: LICENSE
readme: README.md
repository: https://github.com/scottharwell/ansible_on_clouds.setup_and_config.git
tags:
  - cloud
  - azure
  - infrastructure
dependencies:
  awx.awx: '*'
build_ignore:
  - '.tox'
  - '.git'
  - '.github'
  - '.gitignore'