---
- name: Add Red Hat Registry Credential
  awx.awx.credential:
    name: "{{ rh_registry_credential_name | default('Red Hat Registry') }}"
    description: "{{ rh_registry_credential_description | default('Red Hat Registry') }}"
    organization: "{{ rh_registry_credential_organization | default('Default') }}"
    state: present
    credential_type: Container Registry
    controller_host: "{{ controller_host }}"
    inputs:
      username: "{{ lookup('env','RED_HAT_ACCOUNT') }}"
      password: "{{ lookup('env','RED_HAT_PASSWORD') }}"
  no_log: true
- name: Add Azure Credential
  awx.awx.credential:
    name: "{{ azure_credential_name | default('Azure Service Principal') }}"
    description: "{{ azure_credential_description | default('Azure Service Principal') }}"
    organization: "{{ azure_demo_organization | default('Default') }}"
    state: present
    credential_type: Microsoft Azure Resource Manager
    inputs:
      tenant: "{{ lookup('env','AZURE_TENANT_ID') }}"
      subscription: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"
      client: "{{ lookup('env','AZURE_CLIENT_ID') }}"
      secret: "{{ lookup('env','AZURE_CLIENT_SECRET') }}"
    controller_host: "{{ controller_host }}"
  no_log: true
- name: Add Other Credentials
  awx.awx.credential:
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    organization: "{{ item.organization | default('Default') }}"
    state: present
    credential_type: "{{ item.credential_type }}"
    inputs: "{{ item.inputs }}"
    controller_host: "{{ controller_host }}"
  loop: "{{ extra_credentials }}"
  when: (extra_credentials is defined) and (extra_credentials | length > 0)
  no_log: true
