---
- name: Add Custom Azure Execution Environment
  awx.awx.execution_environment:
    name: "{{ azure_ee_name | default('Microsoft Azure Execution Environment') }}"
    image: "{{ azure_ee_image | default('registry.redhat.io/ansible-automation-platform-21/ee-cloud-services-rhel8:latest') }}"
    credential: "{{ azure_ee_registry_credential_name }}"
    state: present
    controller_host: "{{ controller_host }}"
