---
- name: Delete Demo Template
  become: false
  awx.awx.job_template:
    name: Demo Job Template
    state: absent
    controller_host: "{{ controller_host }}"
  when: (delete_demo_project is defined) and (delete_demo_project|bool)
- name: Create Templates
  become: false
  awx.awx.job_template:
    name: "{{ item.name }}"
    job_type: "run"
    organization: "{{ azure_demo_organization | default('') }}"
    inventory: "{{ azure_demo_inventory | default('Demo Inventory') }}"
    project: "{{ azure_demo_project_name | default('Azure Demo') }}"
    extra_vars: "{{ item.extra_vars }}"
    playbook: "project/{{ item.playbook }}"
    credentials: "{{ item.credentials | default(['Azure Service Principal']) }}"
    execution_environment: "{{ azure_ee_name | default('Microsoft Azure Execution Environment') }}"
    state: "present"
    controller_host: "{{ controller_host }}"
  loop: "{{ azure_demo_templates }}"
- name: Create Extra Templates
  become: false
  awx.awx.job_template:
    name: "{{ item.name }}"
    job_type: run
    organization: "{{ item.organization | default('') }}"
    inventory: "{{ item.inventory | default('Demo Inventory') }}"
    project: "{{ item.project }}"
    extra_vars: "{{ item.extra_vars | default({}) }}"
    playbook: "{{ item.playbook }}"
    credentials: "{{ item.credentials | default(None) }}"
    execution_environment: "{{ item.execution_environment | default(None) }}"
    forks: "{{ item.forks | default(0) }}"
    limit: "{{ item.limit | default(None) }}"
    verbosity: "{{ item.verbosity | default(0) }}"
    timeout: "{{ item.timeout | default(0) }}"
    become_enabled: "{{ item.become_enabled | default(False) }}"
    concurrent_jobs_enabled: "{{ item.concurrent_jobs_enabled | default(False) }}"
    ask_credential_on_launch: "{{ item.ask_credential_on_launch | default(False) }}"
    ask_diff_mode_on_launch: "{{ item.ask_diff_mode_on_launch | default(False) }}"
    ask_inventory_on_launch: "{{ item.ask_inventory_on_launch | default(False) }}"
    ask_job_type_on_launch: "{{ item.ask_job_type_on_launch | default(False) }}"
    ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(False) }}"
    ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch | default(False) }}"
    ask_skip_tags_on_launch: "{{ item.ask_skip_tags_on_launch | default(False) }}"
    ask_tags_on_launch: "{{ item.ask_tags_on_launch | default(False) }}"
    ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(False) }}"
    ask_verbosity_on_launch: "{{ item.ask_verbosity_on_launch | default(False) }}"
    diff_mode: "{{ item.diff_mode | default(False) }}"
    job_tags: "{{ item.job_tags | default('') }}"
    job_slice_count: 1
    state: present
    controller_host: "{{ controller_host }}"
  loop: "{{ extra_templates }}"
  when: (extra_templates is defined) and (extra_templates | length > 0)
