---
- name: Add EE Cloud Services Execution Environment
  ansible.controller.execution_environment:
    name: Cloud Services Execution Environment
    description: Red Hat Cloud Services EE
    organization: "{{ awx_organization | default('') }}"
    image: registry.redhat.io/ansible-automation-platform-24/ee-cloud-services-rhel8:latest
    credential: Red Hat Registry
    pull: always
    state: present
  register: cloud_services_ee
  when:
    - seed_validated_content
  tags:
    - ees

- name: Set Cloud Services EE as global default
  ansible.builtin.set_fact:
    default_execution_environment: "{{ cloud_services_ee.id | int }}"
  when: 
    - cloud_services_ee is defined
    - execution_environments.set_cloud_services_ee_default is defined
    - execution_environments.set_cloud_services_ee_default

- name: Add Test Cloud Execution Environment
  ansible.controller.execution_environment:
    name: Cloud EE
    image: quay.io/scottharwell/cloud-ee:latest
    state: present
    pull: always
  register: cloud_ee
  when:
    - seed_content_lab
  tags:
    - ees

- name: Set Cloud EE as global default
  ansible.builtin.set_fact:
    default_execution_environment: "{{ cloud_ee.id | int }}"
  when: 
    - cloud_ee is defined
    - execution_environments.set_cloud_ee_default is defined
    - execution_environments.set_cloud_ee_default
