---
- name: Create localhost inventory
  ansible.controller.inventory:
    name: localhost
    description: localhost
    organization: "{{ awx_organization }}"
    state: present
    variables:
      ansible_python_interpreter: /usr/bin/python3
  tags:
    - inventories

- name: Add localhost host to inventory
  ansible.controller.host:
    name: localhost
    inventory: localhost
    state: present
  tags:
    - inventories

- name: Create Azure Inventory
  ansible.controller.inventory:
    name: Azure
    description: Azure Inventory
    organization: "{{ awx_organization }}"
    state: present
  tags:
    - inventories

- name: Add Azure inventory source
  ansible.controller.inventory_source:
    name: Azure Dynamic Inventory
    description: Creates inventory from Azure sources
    inventory: Azure
    credential: Azure Service Principal
    execution_environment: Harwell - Cloud EE
    overwrite: true
    update_on_launch: true
    organization: "{{ awx_organization }}"
    source: scm
    source_project: Ansible Cloud Content Lab - Azure Roles
    source_path: inventory/inventory.azure_rm.yml
    verbosity: 0
  tags:
    - inventories
