---
- name: Delete Demo Template
  ansible.controller.job_template:
    name: Demo Job Template
    state: absent
  when: (delete_demo_project is defined) and (delete_demo_project | bool)
  tags:
    - templates

- name: Azure - Create Resource Group
  ansible.controller.job_template:
    name: lab.azure_roles.create_resource_group
    inventory: localhost
    playbook: playbook_create_resource_group.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Create RHEL VM
  ansible.controller.job_template:
    name: lab.azure_roles.create_rhel_vm
    inventory: localhost
    playbook: playbook_create_rhel_vm.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      vm_name: "{% raw %}create-rhel-test-{{ lookup('community.general.random_string', length=4, special=false) }}{% endraw %}"
      nic_name: create-rhel-test-nic
      network_sec_group_name: create-rhel-test-sg
      public_ip_name: create-rhel-test-public-ip
      vnet_name: spoke-1-vnet
      subnet_name: spoke-1-subnet
      create_public_ip: true
      ssh_public_key:  "{{ job_templates.ssh_public_key }}"
      admin_password: "{{ job_templates.admin_password }}"
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Delete RHEL VM
  ansible.controller.job_template:
    name: lab.azure_roles.delete_rhel_vm
    inventory: localhost
    playbook: playbook_delete_rhel_vm.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Create Windows Server VM
  ansible.controller.job_template:
    name: lab.azure_roles.create_windows_vm
    inventory: localhost
    playbook: playbook_create_windows_vm.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      vm_name: "{% raw %}create-win-test-{{ lookup('community.general.random_string', length=4, special=false) }}{% endraw %}"
      nic_name: create-win-test-nic
      network_sec_group_name: create-win-test-sg
      public_ip_name: create-win-test-public-ip
      vnet_name: spoke-1-vnet
      subnet_name: spoke-1-subnet
      create_public_ip: true
      admin_password: "{{ job_templates.admin_password }}"
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Delete Windows VM
  ansible.controller.job_template:
    name: lab.azure_roles.delete_windows_vm
    inventory: localhost
    playbook: playbook_delete_windows_vm.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Destroy Resource Group
  ansible.controller.job_template:
    name: lab.azure_roles.delete_resource_group
    inventory: localhost
    playbook: playbook_delete_resource_group.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Create Network Peering Demo
  ansible.controller.job_template:
    name: lab.azure_roles.create_transit_network
    inventory: localhost
    playbook: playbook_create_transit_network.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      priv_network_hosts_pattern: 172.16.*
      priv_network_ssh_user: azureuser
      ansible_ssh_private_key_file_local_path: /home/runner/.ssh/id_rsa_azure_demo # Must exist locally or be mapped in an EE
      ansible_ssh_private_key_file_dest_path: /home/runner/.ssh/id_rsa_azure_demo
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Destroy Network Peering Demo
  ansible.controller.job_template:
    name: lab.azure_roles.delete_transit_network
    project: Ansible Cloud Content Lab - Azure Roles
    playbook: playbook_delete_transit_network.yml
    inventory: localhost
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
    ask_variables_on_launch: true
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Run DNF Update
  ansible.controller.job_template:
    name: lab.azure_roles.update_rhel_vms
    job_type: run
    project: Ansible Cloud Content Lab - Azure Roles
    playbook: playbook_update_rhel_vms.yml
    inventory: Azure
    limit: rhel
    credentials:
      - Azure VM SSH Credential
    become_enabled: true
    job_slice_count: 5
    state: present
  tags:
    - templates

- name: Azure - Install Arc Agent
  ansible.controller.job_template:
    name: lab.azure_roles.arc_install_agent
    inventory: Azure
    playbook: playbook_install_arc_agent.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars: 
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      tenant_id: "{% raw %}{{ lookup('env', 'AZURE_TENANT') }}{% endraw %}"
      subscription_id: "{% raw %}{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}{% endraw %}"
      service_principal_id: "{% raw %}{{ lookup('env', 'AZURE_CLIENT_ID') }}{% endraw %}"
      service_principal_secret: "{% raw %}{{ lookup('env', 'AZURE_SECRET') }}{% endraw %}"
    credentials:
      - Azure VM SSH Credential
      - Azure Service Principal
    limit: rhel
    become_enabled: true
    ask_inventory_on_launch: true
    ask_limit_on_launch: true
  tags:
    - templates

- name: Azure - Enable Arc Extensions
  ansible.controller.job_template:
    name: lab.azure_roles.arc_enable_extensions
    inventory: Azure
    playbook: playbook_enable_arc_extension.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars: 
      resource_group: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      arc_hosts: "{% raw %}{{ hostvars.values() | selectattr('group_names','contains', 'arc') | map(attribute='inventory_hostname') | list }}{% endraw %}"
      extension: azure_monitor_agent # this name is from the extension variable mapping in the content lab collection
    credentials:
      - Azure Service Principal
    ask_variables_on_launch: true
  tags:
    - templates

- name: Azure - Disable Arc Extensions
  ansible.controller.job_template:
    name: lab.azure_roles.arc_disable_extensions
    inventory: Azure
    playbook: playbook_disable_arc_extension.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars: 
      resource_group_name: "{{ azure_resource_group }}"
      region: "{{ azure_region }}"
      arc_hosts: "{% raw %}{{ hostvars.values() | selectattr('group_names','contains', 'arc') | map(attribute='inventory_hostname') | list }}{% endraw %}"
      extension: azure_monitor_agent # this name is from the extension variable mapping in the content lab collection
    credentials:
      - Azure Service Principal
    ask_variables_on_launch: true
  tags:
    - templates

- name: Azure - Replace Log Analytics with Azure Monitor
  ansible.controller.job_template:
    name: lab.azure_roles.arc_replace_log_analytics_with_azure_monitor
    inventory: Azure
    playbook: playbook_replace_log_analytics_with_arc_linux.yml
    project: Ansible Cloud Content Lab - Azure Roles
    extra_vars:
      region: "{{ azure_region }}"
      resource_group: "{{ azure_resource_group }}"
      linux_hosts: "{% raw %}{{ hostvars.values() | selectattr('group_names','contains', 'arc') | map(attribute='inventory_hostname') | list }}{% endraw %}"
    credentials:
      - Azure Service Principal
  tags:
    - templates

- name: Azure - Create Log Analytics Workspace
  ansible.controller.job_template:
    name: lab.azure_roles.create_log_analytics_workspace
    inventory: localhost
    playbook: playbook_create_log_analytics_workspace.yml
    project: Ansible Cloud Content Lab - Azure Roles
    credentials:
      - Azure VM SSH Credential
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      workspace_name: "{{ job_templates.log_ws_name }}"
    limit: rhel
  tags:
    - templates

- name: Azure - Install Log Analytics Agent
  ansible.controller.job_template:
    name: lab.azure_roles.log_analytics_install_agent
    inventory: Azure
    playbook: playbook_install_log_analytics_agent.yml
    project: Ansible Cloud Content Lab - Azure Roles
    credentials:
      - Azure VM SSH Credential
    extra_vars:
      resource_group: "{{ azure_resource_group }}"
      workspace_name: log-ws
    become_enabled: true
    limit: rhel
    ask_inventory_on_launch: true
    ask_limit_on_launch: true
  tags:
    - templates

- name: Azure - Uninstall Log Analytics Agent
  ansible.controller.job_template:
    name: lab.azure_roles.log_analytics_uninstall_agent
    inventory: Azure
    playbook: playbook_uninstall_log_analytics_agent.yml
    project: Ansible Cloud Content Lab - Azure Roles
    credentials:
      - Azure VM SSH Credential
    become_enabled: true
    ask_inventory_on_launch: true
    ask_limit_on_launch: true
  tags:
    - templates

- name: Run Ephemeral Workload Test
  ansible.controller.job_template:
    name: Azure Demos - Ephemeral Workload Test
    job_type: run
    project: Ansible - Azure Demo
    playbook: project/emphemeral_workload_test.yml
    inventory: localhost
    credentials:
      - Ansible Automation Controller
      - Azure Service Principal
      - Azure VM SSH Credential
    become_enabled: true
    job_slice_count: 1
    state: present
  tags:
    - templates
