---
- name: Delete Demo Project
  ansible.controller.project:
    name: Demo Project
    state: absent
  when:
    - delete_demo_project is defined
    - (delete_demo_project | bool)
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Demo Project
  ansible.controller.project:
    name: Ansible Cloud Content Lab - Azure Demo
    description: Azure Demo
    default_environment: Cloud EE
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm.url: "{{ projects.azure_demo_project.url }}"
    state: present
  when:
    - seed_content_lab
  register: content_lab_project_demo
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Project
  ansible.controller.project:
    name: Ansible Cloud Content Lab - Azure Roles
    description: Ansible Cloud Content Lab - Azure Roles
    default_environment: Cloud EE
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm.url: "{{ projects.azure_lab_roles.url }}"
    state: present
  when:
    - seed_content_lab
  register: content_lab_project_azure
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab AWS Project
  ansible.controller.project:
    name: Ansible Cloud Content Lab - AWS Roles
    description: Ansible Cloud Content Lab - AWS Roles
    default_environment: Cloud EE
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm.url: "{{ projects.aws_lab_roles.url }}"
    state: present
  when:
    - seed_content_lab
  register: content_lab_project_aws
  tags:
    - projects
    - aws

- name: Add Ansible Cloud Seeded Content Project
  ansible.controller.project:
    name: Ansible Validated Content - Azure Demos
    description: Ansible Automation Platform Cloud Seeded Content - Azure
    default_environment: "{{ cloud_services_ee.name }}"
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm_url: "{{ projects.azure_seeded_content.url }}"
    state: present
  when:
    - seed_validated_content
    - cloud_services_ee is present
  register: seeded_content_project_azure
  tags:
    - projects
    - azure
