---
- name: Deploy Demo AoC Site
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
  tasks:
  
    - name: Configure Demo Site
      ansible.builtin.import_role:
        name: roles/azure
