---
name: validation-checks

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pre-commit
        run: sudo pip3 install pre-commit

      - name: Run pre-commit
        run: pre-commit run
